# +TITLE:Start logging online learning progress


* 2018/9/28
** Learn to make HTML5 GAME on Udemy (excited) 
*** Firstly, need to install XAMPP to run localhost
**** To install .run files on Ubuntu, first change its permission then ./xxx.run
* 2018/9/26
** Learn HTML on Codeacademy
*** When inserting a hyperlink, there are multiple ways to open this link in.
**** use attribute  "target" to control this behavior 
**** "_self" opens in current tab, "_blank" new tab, "_parent" the tab which opened this tab , "_top" the earliest parent that open this tab
**** If there is no parent, open in "_self"
* 2018/9/25
** Start logging daily learning 
** Learn HTML on Codeacademy
*** <span> tag works kind of like a text style changer within an element like <p>  
*** the attribute "alt" is used to put a desciption to the image , that way people who cannot load the image can view descriptions
**** The alt also can be used by crawler of search engines that way, alt can improve the ranking of my site.
*** For video, you need both opening and closing tags. The text in between the texts will be displayed if the browser do not support video.
